spring.application.name=arenamatch

spring.datasource.url=jdbc:postgresql://localhost:5432/arenamatch-dev
spring.datasource.username=arena
spring.datasource.password=arena123
spring.datasource.driver-class-name=org.postgresql.Driver
flyway.locations=db/migrations

spring.flyway.enabled=true
joinfaces.primefaces.theme=arya

arenamatch.api.base-url=http://localhost:8080
arenamatch.jwt.secret=arenamatch-dev-secret-change-me-please-2026-with-at-least-32-chars
arenamatch.jwt.expiration-seconds=43200

google.maps.apikey=AIzaSyAOD3C5_WQJN6nZ0IcSgJTaLVhxft7MOy0

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=arenamatch.app@gmail.com
spring.mail.password=vekb zzpb qdlz wrlh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.servlet.session.timeout=30m

spring.profiles.active=dev
